// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_dXLfjDgOz2bRjk73oqTcW_ViRkuEnPg',
    appId: '1:337741082788:web:a48c531177eeb6c05cb631',
    messagingSenderId: '337741082788',
    projectId: 'arsenal-hardwarefix',
    authDomain: 'arsenal-hardwarefix.firebaseapp.com',
    storageBucket: 'arsenal-hardwarefix.firebasestorage.app',
    measurementId: 'G-ZPS9D6HZC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx4O8TWohwxHonJX41EMsNVgxhMbrGe2s',
    appId: '1:337741082788:android:a701f37a54af3e755cb631',
    messagingSenderId: '337741082788',
    projectId: 'arsenal-hardwarefix',
    storageBucket: 'arsenal-hardwarefix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDePKyMTAtq5pRKLtCIEc9aRiOEnpToz58',
    appId: '1:337741082788:ios:bc26460bb25ee95b5cb631',
    messagingSenderId: '337741082788',
    projectId: 'arsenal-hardwarefix',
    storageBucket: 'arsenal-hardwarefix.firebasestorage.app',
    iosClientId: '337741082788-4n5d2b7jr3helun2tvjfnf7r0u9u0et5.apps.googleusercontent.com',
    iosBundleId: 'com.example.wetried.exe.arsenal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDePKyMTAtq5pRKLtCIEc9aRiOEnpToz58',
    appId: '1:337741082788:ios:bc26460bb25ee95b5cb631',
    messagingSenderId: '337741082788',
    projectId: 'arsenal-hardwarefix',
    storageBucket: 'arsenal-hardwarefix.firebasestorage.app',
    iosClientId: '337741082788-4n5d2b7jr3helun2tvjfnf7r0u9u0et5.apps.googleusercontent.com',
    iosBundleId: 'com.example.wetried.exe.arsenal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_dXLfjDgOz2bRjk73oqTcW_ViRkuEnPg',
    appId: '1:337741082788:web:2ffa4b679a4ff30a5cb631',
    messagingSenderId: '337741082788',
    projectId: 'arsenal-hardwarefix',
    authDomain: 'arsenal-hardwarefix.firebaseapp.com',
    storageBucket: 'arsenal-hardwarefix.firebasestorage.app',
    measurementId: 'G-6X8W4H9D1T',
  );

}